// Offline support is opt-in only — this worker never caches a whole book's
// content just because it was fetched. Two things populate Cache Storage
// explicitly:
//  - download.js's "Tải xuống" button, into a "book-<id>" cache, per book.
//  - download.js's precacheAppShell(), into "app-shell-v1" — the fixed
//    handful of files (download.html, chapter-shell.html, reader.js,
//    download.js, manifest, icons) the PWA needs just to boot and show the
//    Download page with no network at all. Refreshed each time the
//    Download page loads online.
// The one deliberate exception is cover art: any successfully-loaded cover
// — downloaded book or not — gets opportunistically written into a shared
// "covers-v1" cache (see COVER_URL_RE/cacheCoverIfMatch below), since it's
// small, immutable once generated by build_library.py, and otherwise had
// no way to survive offline or avoid a re-fetch for undownloaded books.
//
// SW_VERSION is stamped at deploy time (see build/deploy step) — logged so
// a stale cached copy is obvious at a glance instead of a guess.
const SW_VERSION = '__DEPLOY_VERSION__';
console.log(`sw.js: version ${SW_VERSION} evaluating`);

self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (e) =>
  e.waitUntil(
    self.clients.claim().then(async () => {
      // console.log() in this file goes to the Service Worker's OWN
      // Inspector target, not the page's — postMessage puts the version
      // somewhere download.js can actually log it from the console
      // that's already open on the page.
      const clients = await self.clients.matchAll();
      clients.forEach((client) => client.postMessage({ type: 'sw-version', version: SW_VERSION }));
    })
  )
);
// A page that was already open (not just newly navigated) when this SW
// activates won't get the message above until ITS next activate — this
// covers that page by replying to an explicit request instead of only
// broadcasting once on our own activation.
self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'get-sw-version') {
    e.source.postMessage({ type: 'sw-version', version: SW_VERSION });
  }
});

// Every "/books/<id>/chapters/<chapter>.html" URL is served by the same
// static chapter-shell.html file server-side (see server.py's
// chapter_shell route) — reuse that one cached copy for ANY chapter URL
// that isn't reachable live, instead of needing a cache entry per chapter
// URL for a file that's byte-identical across all ~3000 of them.
const CHAPTER_SHELL_RE = /^\/books\/\d+\/chapters\/[^/]+\.html$/;
const BOOK_URL_RE = /^\/books\/(\d+)\//;
const APP_SHELL_CACHE = 'app-shell-v1'; // must match download.js's APP_SHELL_CACHE

// Cover art for books that were never explicitly downloaded (see
// downloadBook() in download.js) has nowhere to persist: it only ever lands
// in a "book-<id>" cache once the whole book is, so browsing the catalog
// grid or a book's own page for anything not downloaded re-fetched the
// same cover image from the server every single time, and had nothing to
// fall back to offline. This cache holds cover art on its own, independent
// of any per-book download — filled in opportunistically (see
// cacheCoverIfMatch()) the first time any page successfully loads a given
// cover, no explicit "download" action required.
const COVER_URL_RE = /^\/books\/\d+\/cover\.[A-Za-z0-9]+$/;
const COVERS_CACHE = 'covers-v1';

// Which single cache a URL's fallback can possibly be in — book content
// (chapter data/meta.json/index.html/cover) only ever lands in that book's
// own "book-<id>" cache (see download.js's downloadBook()); everything
// else only ever lands in "app-shell-v1" (precacheAppShell()). Opening
// the one cache that can actually contain the match, instead of an
// unscoped caches.match() that has to open and scan every cache (a book
// with a few thousand chapters means a few thousand entries in that one
// cache alone), was step one of speeding this up — worth keeping even
// after the bigger fix below, since it's still less work per lookup.
function cacheNameFor(pathnameOrRequest) {
  const pathname = typeof pathnameOrRequest === 'string' ? pathnameOrRequest : new URL(pathnameOrRequest.url).pathname;
  const m = pathname.match(BOOK_URL_RE);
  return m ? `book-${m[1]}` : APP_SHELL_CACHE;
}

// The real fix: don't ask "is the network there?" via a dedicated probe
// request of its own — a probe has to share the same connection pool and
// bandwidth as everything else a page load fires at once (precacheAppShell()'s
// 9 files, a book's many chapter fetches while downloading, a grid of cover
// images...), and under that contention the probe itself was the thing most
// likely to starve and time out, misreporting "offline" while the network
// was actually fine, just busy. Confirmed live: any page with its own
// fetching in flight would trip this false positive reliably, not
// occasionally.
//
// So there is no separate probe. The ONE thing that decides "believed
// offline" is the outcome of a real request a caller already needed for its
// own sake — nothing extra fired just to ask. A single failure marks
// "believed offline" for a short window so the next few requests (which,
// for one page load, tend to arrive within milliseconds of each other) skip
// straight to cache instead of each re-discovering the same outage on its
// own timeout. Any single success — including the bounded retry attempted
// below for a cache-miss while "believed offline" — clears it immediately,
// so a one-off blip doesn't pin the app to "offline" any longer than the
// one request it takes to prove otherwise.
const BELIEVED_OFFLINE_TTL_MS = 5000;
const ONLINE_FETCH_TIMEOUT_MS = 3000;
const OFFLINE_FETCH_TIMEOUT_MS = 600;
let believedOfflineUntil = 0; // epoch ms; Date.now() < this means "believed offline"

function isBelievedOffline() {
  // navigator.onLine reflects the OS network interface (WiFi/cellular on or
  // off) — only ever used here as a short-circuit TO "offline", never to
  // "online", since it says nothing about whether the server is actually
  // reachable (interface up, server down is still a real case the request
  // outcome below has to catch on its own).
  if (self.navigator && self.navigator.onLine === false) return true;
  return Date.now() < believedOfflineUntil;
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  const fallbackUrl = CHAPTER_SHELL_RE.test(url.pathname) ? '/chapter-shell.html' : req;
  event.respondWith(handleFetch(req, fallbackUrl));
});

// Every fetch() this worker issues goes through here — no bare,
// unbounded fetch() anywhere else in the file. A previous version left
// exactly one such call in the "believed offline, not cached either" last
// resort below, reasoning it'd rarely be hit; live testing showed
// otherwise (a home page with more books than have been explicitly
// downloaded means MOST cover images take that exact path, so on a
// genuinely offline load every single one of them was a bare fetch()
// free to hang far longer than any timeout elsewhere in this file).
async function fetchWithTimeout(request, ms) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ms);
  try {
    return await fetch(request, { signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

// Cover URLs additionally fall back to COVERS_CACHE — populated by ANY page
// that successfully loaded that cover, not just a downloaded book's own
// "book-<id>" cache (which matchWithFallback's normal cacheNameFor() lookup
// already covers on its own).
async function matchWithFallback(fallback) {
  const cache = await caches.open(cacheNameFor(fallback));
  const cached = await cache.match(fallback, { ignoreVary: true });
  if (cached) return cached;
  const pathname = typeof fallback === 'string' ? fallback : new URL(fallback.url).pathname;
  if (!COVER_URL_RE.test(pathname)) return undefined;
  const coversCache = await caches.open(COVERS_CACHE);
  return coversCache.match(fallback, { ignoreVary: true });
}

// Fire-and-checked (awaited, but never lets a caching failure fail the
// response itself) after any successful fetch — this is what actually
// populates COVERS_CACHE, independent of whether the book it belongs to
// was ever explicitly downloaded.
async function cacheCoverIfMatch(request, response) {
  if (!response.ok || !COVER_URL_RE.test(new URL(request.url).pathname)) return;
  try {
    const cache = await caches.open(COVERS_CACHE);
    await cache.put(request, response.clone());
  } catch (e) {
    // Storage quota or similar — losing the offline cover cache for this
    // one image isn't worth failing the actual response over.
  }
}

async function handleFetch(request, fallback) {
  if (isBelievedOffline()) {
    // Believed offline from a recent failure — go straight to cache, no
    // network attempt (and nothing to time out) for this resource at all.
    const cached = await matchWithFallback(fallback);
    if (cached) return cached;
    // Not cached either — the belief could be stale (e.g. the network
    // recovered, or the failure that set it was itself an unrelated fluke),
    // so still genuinely try the network as a last resort rather than
    // failing on our own say-so — but bounded, not a bare fetch().
    const response = await fetchWithTimeout(request, OFFLINE_FETCH_TIMEOUT_MS);
    believedOfflineUntil = 0;
    await cacheCoverIfMatch(request, response);
    return response;
  }

  // Believed online — network first, bounded by an abort-backed timeout in
  // case THIS particular request stalls (flaky connection, not a hard
  // "offline"). A failure here is what actually marks "believed offline" —
  // see the comment above isBelievedOffline() for why that's the only
  // signal used, instead of a dedicated probe.
  try {
    const response = await fetchWithTimeout(request, ONLINE_FETCH_TIMEOUT_MS);
    await cacheCoverIfMatch(request, response);
    return response;
  } catch (err) {
    believedOfflineUntil = Date.now() + BELIEVED_OFFLINE_TTL_MS;
    const cached = await matchWithFallback(fallback);
    if (cached) return cached;
    throw err;
  }
}
